### ISSUE TITLE
Missing Logs from Containers in a CrashLoop

### ISSUE THREAD

**Issue by chen-anders** [zalando-incubator/kubernetes-log-watcher#29]
I've noticed that logs from containers that may have been in a crash-loop do not get collected. The observed behavior is that a new "pause" docker container (whose logs get ignored) gets created under a different container ID (in docker) when the crashloop is detected and that somehow the logs of the prior crashing container are abandoned.

Test crash-looping container:

```
apiVersion: v1
kind: Pod
metadata:
  name: crashloop
  labels:
    application: crashloop
    version: '1.0'
spec:
  containers:
  - name: container
    image: python:3.5
    command: ["/bin/sh"]
    args: ["-c", "sleep 3; echo 'hello'; exit 1;"]
```

We currently have our logs going up to Scalyr.
