### ISSUE TITLE
Support custom parsers for log targets (Scalyr)

### ISSUE THREAD

**Issue by mohabusama** [zalando-incubator/kubernetes-log-watcher#36]
It is often required that an application needs specific parser other than the default ``json``.

The way this could be inspected is via ``labels`` or ``annotations``.

```yaml

labels:
    scalyr-parser: "my-app-my-custom-parser"  # meh!
annotations:
    <namespace>/scalyr-parser: '[{"container": "my-app", "parser": "my-custom-parser"}]'
```
